// Decompiled with JetBrains decompiler
// Type: StudentActionType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: FD17A22F-B301-43EA-811A-FA797D0BA442
// Assembly location: C:\YandereSimulator\YandereSimulator\YandereSimulator_Data\Managed\Assembly-CSharp.dll

public enum StudentActionType
{
  AtLocker,
  Socializing,
  Gaming,
  Shamed,
  Slave,
  Relax,
  SitAndTakeNotes,
  Peek,
  ClubAction,
  SitAndSocialize,
  SitAndEatBento,
  ChangeShoes,
  GradePapers,
  Patrol,
  Read,
  Texting,
  Mourn,
  Cuddle,
  Teaching,
  SearchPatrol,
  Wait,
  Clean,
  Gossip,
  Graffiti,
  Bully,
  Follow,
  Sulk,
  Sleuth,
  Stalk,
  Sketch,
  Sunbathe,
  Shock,
  Miyuki,
  Meeting,
  Lyrics,
  Practice,
  Sew,
  Paint,
  UpdateAppearance,
  LightCig,
  PlaceBag,
  Sleep,
  LightFire,
  Jog,
  PrepareFood,
  Perform,
  PhotoShoot,
  GravurePose,
  Guard,
  Random,
}
