public enum YandereInteractionType
{
	Idle = 0,
	Apologizing = 1,
	Compliment = 2,
	Gossip = 3,
	Bye = 4,
	FollowMe = 6,
	GoAway = 7,
	DistractThem = 8,
	ClubInfo = 10,
	ClubJoin = 11,
	ClubQuit = 12,
	ClubBye = 13,
	ClubActivity = 14,
	NamingCrush = 17,
	ChangingAppearance = 18,
	Court = 19,
	Advice = 20,
	Feed = 21,
	TaskInquiry = 22,
	GivingSnack = 23,
	AskingForHelp = 24,
	SendingToLocker = 25
}
