using System;
using System.Collections.Generic;
using UnityEngine;

// Token: 0x02000514 RID: 1300
public class YanSaveIdentifier : MonoBehaviour
{
	// Token: 0x0600216A RID: 8554 RVA: 0x001EC2C8 File Offset: 0x001EA4C8
	public static GameObject GetObject(string id)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == id)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x0600216B RID: 8555 RVA: 0x001EC330 File Offset: 0x001EA530
	public static GameObject GetObject(SerializedGameObject serializedGameObject)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == serializedGameObject.ObjectID)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x0600216C RID: 8556 RVA: 0x001EC39C File Offset: 0x001EA59C
	public void OnEnable()
	{
		if (!YanSaveIdentifier.Identifiers.Contains(this))
		{
			YanSaveIdentifier.Identifiers.Add(this);
		}
		if (string.IsNullOrEmpty(this.ObjectID))
		{
			this.ObjectID = base.gameObject.name;
		}
	}

	// Token: 0x0600216D RID: 8557 RVA: 0x001EC3D4 File Offset: 0x001EA5D4
	public void OnDestroy()
	{
		YanSaveIdentifier.Identifiers.Remove(this);
	}

	// Token: 0x04004982 RID: 18818
	public string ObjectID;

	// Token: 0x04004983 RID: 18819
	[HideInInspector]
	public bool AutoGenerated;

	// Token: 0x04004984 RID: 18820
	[HideInInspector]
	public List<Component> EnabledComponents = new List<Component>();

	// Token: 0x04004985 RID: 18821
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledProperties = new List<DisabledYanSaveMember>();

	// Token: 0x04004986 RID: 18822
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledFields = new List<DisabledYanSaveMember>();

	// Token: 0x04004987 RID: 18823
	[HideInInspector]
	public bool InitializedInspector;

	// Token: 0x04004988 RID: 18824
	private static List<YanSaveIdentifier> Identifiers = new List<YanSaveIdentifier>();
}
