using System;
using System.Collections.Generic;
using UnityEngine;

// Token: 0x0200050F RID: 1295
public class YanSaveIdentifier : MonoBehaviour
{
	// Token: 0x0600214C RID: 8524 RVA: 0x001E9988 File Offset: 0x001E7B88
	public static GameObject GetObject(string id)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == id)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x0600214D RID: 8525 RVA: 0x001E99F0 File Offset: 0x001E7BF0
	public static GameObject GetObject(SerializedGameObject serializedGameObject)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == serializedGameObject.ObjectID)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x0600214E RID: 8526 RVA: 0x001E9A5C File Offset: 0x001E7C5C
	public void OnEnable()
	{
		if (!YanSaveIdentifier.Identifiers.Contains(this))
		{
			YanSaveIdentifier.Identifiers.Add(this);
		}
		if (string.IsNullOrEmpty(this.ObjectID))
		{
			this.ObjectID = base.gameObject.name;
		}
	}

	// Token: 0x0600214F RID: 8527 RVA: 0x001E9A94 File Offset: 0x001E7C94
	public void OnDestroy()
	{
		YanSaveIdentifier.Identifiers.Remove(this);
	}

	// Token: 0x04004906 RID: 18694
	public string ObjectID;

	// Token: 0x04004907 RID: 18695
	[HideInInspector]
	public bool AutoGenerated;

	// Token: 0x04004908 RID: 18696
	[HideInInspector]
	public List<Component> EnabledComponents = new List<Component>();

	// Token: 0x04004909 RID: 18697
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledProperties = new List<DisabledYanSaveMember>();

	// Token: 0x0400490A RID: 18698
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledFields = new List<DisabledYanSaveMember>();

	// Token: 0x0400490B RID: 18699
	[HideInInspector]
	public bool InitializedInspector;

	// Token: 0x0400490C RID: 18700
	private static List<YanSaveIdentifier> Identifiers = new List<YanSaveIdentifier>();
}
