using System;
using System.Collections.Generic;
using UnityEngine;

// Token: 0x0200051B RID: 1307
public class YanSaveIdentifier : MonoBehaviour
{
	// Token: 0x06002193 RID: 8595 RVA: 0x001F004C File Offset: 0x001EE24C
	public static GameObject GetObject(string id)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == id)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x06002194 RID: 8596 RVA: 0x001F00B4 File Offset: 0x001EE2B4
	public static GameObject GetObject(SerializedGameObject serializedGameObject)
	{
		foreach (YanSaveIdentifier yanSaveIdentifier in YanSaveIdentifier.Identifiers)
		{
			if (yanSaveIdentifier.ObjectID == serializedGameObject.ObjectID)
			{
				return yanSaveIdentifier.gameObject;
			}
		}
		return null;
	}

	// Token: 0x06002195 RID: 8597 RVA: 0x001F0120 File Offset: 0x001EE320
	public void OnEnable()
	{
		if (!YanSaveIdentifier.Identifiers.Contains(this))
		{
			YanSaveIdentifier.Identifiers.Add(this);
		}
		if (string.IsNullOrEmpty(this.ObjectID))
		{
			this.ObjectID = base.gameObject.name;
		}
	}

	// Token: 0x06002196 RID: 8598 RVA: 0x001F0158 File Offset: 0x001EE358
	public void OnDestroy()
	{
		YanSaveIdentifier.Identifiers.Remove(this);
	}

	// Token: 0x040049E0 RID: 18912
	public string ObjectID;

	// Token: 0x040049E1 RID: 18913
	[HideInInspector]
	public bool AutoGenerated;

	// Token: 0x040049E2 RID: 18914
	[HideInInspector]
	public List<Component> EnabledComponents = new List<Component>();

	// Token: 0x040049E3 RID: 18915
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledProperties = new List<DisabledYanSaveMember>();

	// Token: 0x040049E4 RID: 18916
	[HideInInspector]
	public List<DisabledYanSaveMember> DisabledFields = new List<DisabledYanSaveMember>();

	// Token: 0x040049E5 RID: 18917
	[HideInInspector]
	public bool InitializedInspector;

	// Token: 0x040049E6 RID: 18918
	private static List<YanSaveIdentifier> Identifiers = new List<YanSaveIdentifier>();
}
